# Generated by Django 4.2 on 2023-06-21 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doors_opened', models.BooleanField(blank=True, default=True, null=True)),
                ('elevator_number', models.IntegerField(blank=True, null=True)),
                ('current_floor', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('is_working', models.BooleanField(blank=True, default=True, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'STEADY'), (1, 'GOING_UP'), (2, 'GOING_DOWN')], default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Elevator_System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=225, null=True)),
                ('minimum_floor', models.IntegerField(blank=True, default=0, null=True)),
                ('maximum_floor', models.IntegerField(blank=True, null=True)),
                ('number_of_elevators', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElevatorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_floor', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('to_floor', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.elevator')),
            ],
        ),
        migrations.AddField(
            model_name='elevator',
            name='elevator_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.elevator_system'),
        ),
    ]
